# Generated by Django 5.0.1 on 2024-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='player_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
