# Generated by Django 5.0.1 on 2024-03-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_alter_userdata_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='player_id',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
