# Generated by Django 5.0.1 on 2024-04-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0001_initial'),
        ('team_management', '0002_initial'),
        ('tournament_management', '0003_alter_tournament_description_alter_tournament_ground_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=105)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=30)),
                ('toss_winner', models.IntegerField(blank=True, null=True)),
                ('toss_decision', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('round', models.IntegerField(default=1)), 
                ('number_of_overs', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(blank=True, max_length=150)),
                ('ground', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='match_management.ground')),
                ('opponent_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_opponent_one', to='team_management.team')),
                ('opponent_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_opponent_two', to='team_management.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_winner', to='team_management.team')),
            ],
            options={
                'db_table': 'match',
            }, 
        ),
    ]
