# Generated by Django 5.0.1 on 2024-04-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0002_matches'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matches',
            table='match_fixtures',
        ),
    ]
