# Generated by Django 5.0.1 on 2024-04-11 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_management', '0003_alter_matches_table'),
        ('team_management', '0002_initial'),
        ('tournament_management', '0003_alter_tournament_description_alter_tournament_ground_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('number_of_matches', models.IntegerField(blank=True, null=True)),
                ('number_of_win', models.IntegerField(blank=True, null=True)),
                ('number_of_losses', models.IntegerField(blank=True, null=True)),
                ('number_of_draws', models.IntegerField(blank=True, null=True)),
                ('run_rate', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_management.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.tournament')),
            ],
            options={
                'db_table': 'point_table',
            },
        ),
    ]
