# Generated by Django 5.0.1 on 2024-05-09 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match_management', '0004_pointtable'),
        ('team_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_no', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('extras', models.IntegerField(blank=True, default=0)),
                ('type_of_extras', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
                ('wicket', models.IntegerField()),
                ('type_of_dismissal', models.IntegerField()),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_batting', to='team_management.team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_as_bowler', to=settings.AUTH_USER_MODEL)),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_bowling', to='team_management.team')),
                ('dismissed_by_bowler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_got_bowler', to=settings.AUTH_USER_MODEL)),
                ('dismissed_by_fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicket_got_fielder', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_as_striker', to='match_management.matches')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_as_non_striker', to=settings.AUTH_USER_MODEL)),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_as_striker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
    ]
