# Generated by Django 5.0.1 on 2024-05-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='over_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
