# Generated by Django 5.0.1 on 2024-05-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0002_deliveries_over_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='type_of_extras',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
