# Generated by Django 5.0.1 on 2024-05-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0003_alter_deliveries_type_of_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='type_of_extras',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
