# Generated by Django 5.0.1 on 2024-05-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_management', '0004_alter_deliveries_type_of_extras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='dismissed_by_bowler',
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='type_of_dismissal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
