# Generated by Django 5.0.1 on 2024-03-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team_management', '0001_initial'),
        ('tournament_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament_management.tournament'),
        ),
        migrations.AddField(
            model_name='squad',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_management.team'),
        ),
    ]
