# Generated by Django 5.0.1 on 2024-03-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=55)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('ground', models.CharField(max_length=50)),
                ('organizer_name', models.CharField(max_length=50)),
                ('organizer_contact', models.CharField(max_length=15)),
                ('tournament_category', models.CharField(max_length=50)),
                ('ball_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tournament',
            },
        ),
    ]
