# Generated by Django 5.0.1 on 2024-03-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ground',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='venue',
            field=models.CharField(max_length=128),
        ),
    ]
